# Active : Blue
upstream active_backend {
    server api-green:8000;
}

# Standby : Green (pret mais pas de trafic)
upstream standby_backend {
    server api-green:8000;
}

server {
    listen 80;

    # Tout le trafic va vers l'environnement actif
    location / {
        proxy_pass http://active_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Endpoint de test pour le standby
    location /test-standby/ {
        proxy_pass http://standby_backend/;
        proxy_set_header Host $host;
    }
}